### ISSUE TITLE
Add support for ICD-9

### ISSUE THREAD

**Issue by salmasian** [ellessenne/comorbidity#1]
It would be extremely helpful if ICD-9 support is also added (based on the [Deyo _et al._ paper](https://www.ncbi.nlm.nih.gov/pubmed/1607900) for Charlson, and a similar source for Elixhauser).

**Comment by ellessenne** [comment]
Hi!
I am not really familiar with ICD-9 coding, what is the difference between the Deyo _et al_. paper and the [Quan _et al_.](https://www.ncbi.nlm.nih.gov/pubmed/16224307) paper? Is it ICD-9 vs ICD-9-CM?

**Comment by aalexandersson** [comment]
Hojjat: I agree. However, the R package icd already does this though its AHRQ
Elixhauser implementation is dubious.

Alessandro: No, both Deyo et al. (1992) and Quan et al. (2005) use ICD-9-CM
codes as starting point. Deyo et al. coded only Charlson (1987)
comorbidities whereas Quan et al. also code Elixhauser (1998), and for both
ICD-9-CM and ICD-10.

**Comment by salmasian** [comment]
The `icd` package is not well maintained, and cannot handle even modest-size data. I have found your package extremely useful, and I thin it would be great if you would extend it to support ICD-9 too!

**Comment by ellessenne** [comment]
@aalexandersson,
Thanks for the clarification! I will refer to the Quan _et al_. paper then.

@salmasian,
I will definitely look into adding support for ICD-9-CM coding, please keep an eye on this issue as I start working on it. Do you know (by any chance) if it is safe to just disregard any punctuation (e.g. the dots) when identifying/recognising ICD-9 codes? With ICD-10 that works well!

**Comment by salmasian** [comment]
@ellessenne the dot should be remove from the ICD-9 input, before checking it against the Deyo/Quan lists.

**Comment by ellessenne** [comment]
@salmasian Ok thanks! It should be enough to add a `charlson_icd9` internal function that gets called from the main `comorbidity` function!

**Comment by aalexandersson** [comment]
@ellessenne Please also add an elixhauser_icd9 function (ideally AHRQ
version) because Elixhauser is often regarded as an improvement over
Charlson-Deyo. I am not aware of anything better than icd for ICD-9-CM in
R. There are some more options in Stata and SAS.

@salmasian How bad is the performance in icd? Does it stop working at
thousands of records or at millions or what is modest-size data here to
you? I recommended icd because the documentation looks good and it works on
the small Vermont sample data it comes with. But I have not tried the
package on realistic datasets. I need to work with complicated cancer
datasets that have about 4 million observations. Your comment makes me very
concerned about the usefulness of the package icd.
