### ISSUE TITLE
Is parallel processing actually supported?

### ISSUE THREAD

**Issue by benskov** [ellessenne/comorbidity#30]
This is a very nice package which has saved me quite some time, as others have already highlighted. The paper proposed for citation states that, "Parallel computing is supported out of the box to mitigate this potential problem, with no additional programming required by the user: it is sufficient to set the argument parallel = TRUE when calling comorbidity." (last paragraph on p. 1 in https://joss.theoj.org/papers/10.21105/joss.00648). Was this feature removed, or has it never made it into the released version? It's not in the documentation, the source code does not seem to provide parallelisation, and using the argument `parallel = TRUE` gives the expected error message that it's an unused argument.

Give me a shout if I you need a hand implementing this feature.

Cheers,
Ben

**Comment by ellessenne** [comment]
Hi @benskov,
That was actually implemented (at the time of the paper being written) but has since been removed (as the current implementation based on {data.table} is actually way faster than the previous parallel one). 
We're actually in the process of moving to an even faster scoring algorithm (the one underlying the {icd} package), but time is very limited recently so I'm hoping to get this out soon-ish!
Cheers,
Alessandro
