### ISSUE TITLE
Data types in `help()`-text, `assign0` specifically

### ISSUE THREAD

**Issue by dsjoho** [ellessenne/comorbidity#61]
Hi! Thanks for writing this package.

It's harder than I'd like as a new user to start using it, since e.g. `help(comorbidity)` doesn't specify very clearly what is expected to each argument. The worst issue is for `assign0` which has no mention of data type, but a long list of what comorbidites are affected. I had to read the example to see that it expected a logical. Adding this would also make the on-typing suggestion more helpful.

(And for further improvements I suppose that `id` and `code` could be improved to read "Column name of x" instead of just "Column of x", which had me initially wondering if the function wanted that vector extracted from `x` beforehand, or if it was just the name - thankfully the examples at the bottom of the help-text answered my question. It might be 100% argued that this was a weird idea of mine, so discard if you find this perfectly clear already.)

The help text for `tidy.codes` on the other hand is for instance very clear!

I suggest:
- Add "If TRUE; " to the beginning of the assign0-helptext.
- Add a small example of what assign0 does to the examples - preferably for score impact as well.

**Comment by ellessenne** [comment]
Hi @dsjoho, thanks for your feedback, I appreciate it. I will have a go at improving the documentation, and keep you posted on this issue here. Many thanks again!

**Comment by ellessenne** [comment]
Hi again, I did some edits to documentation that you can check online by navigating [here](https://ellessenne.github.io/comorbidity/index.html). Any feedback would be very much appreciated if you could check it out!

**Comment by dsjoho** [comment]
Wonderful! Now it's very clear. A bit verbose even, but I'd rather have it like this as a new user. Looks good to me!
The examples for assign0 also clarified, the only thing I still want to explore myself would be how/if the weighting is affected.

One extra thing (that I should perhaps put as  a separate issue, but since it's documentation related): the documentation references
```
vignette("01-introduction", package = "comorbidity")
vignette("02-comorbidity-scores", package = "comorbidity")
```

but the actual vignettes start with A, B, in the R/vignette folder. 
Running `vignette(package="comorbidity")` with comorbidity 1.0.3 yields

```
Vignettes in package ‘comorbidity’:

A-introduction    Introduction (source, html)
B-comorbidity-scores
                  Supported Comorbidity Mappings and
                  Scores (source, html)
                                                      
```

I thus think the reference in the documentation is old?

**Comment by ellessenne** [comment]
For `assign0` in `score()`, I added an example [there too](https://ellessenne.github.io/comorbidity/reference/score.html) – loosely speaking, `assign0` can have two effects:
1. When identifying comorbidities,
2. When combining them (to avoid things being _counted_ twice).

Now, there is no default for this argument because I feel that _there is no good default here_, and I like users being aware of what they ask the code to do. Both can be combined and give different results, depending on what the end user is looking for in the end. 

Finally, good catch with the vignettes' names! 
They had indeed been renamed some time ago, and I must have forgot to update the documentation; should be fixed now.
